@echo off
echo          R B 2 - 0 0 1
echo.
echo CONFIDENTIAL TO BETA TESTERS ONLY.
echo IF YOU HAVE THIS AND NOT PART OF
echo THE BETA TESTERS THEN YOU WILL BE
echo TRACKED BY KK64.
pause
cls
echo WHAT IS NEW IN RB2-001
echo.
echo we have a calculator and the gui is coming soon.
echo.
echo SNEAK PEEKS OF FEATURES
echo.
echo GUI coming soon! 
pause
cls
echo Enjoy OpenOS!
RB2-001.bat