@echo off
echo          R B 1 - 0 0 2
echo.
echo CONFIDENTIAL TO ZEROAIR INFINITY
echo IF YOU HAVE THIS AND NOT PART OF
echo ZEROAIR INFINITY THEN YOU WILL BE
echo TRACKED BY KK64.
pause
cls
echo WHAT IS NEW IN RB1-002
echo.
echo Bootable! Its not an OE anymore!
echo Apps! Open them with the terminal!
echo.
echo SNEAK PEEKS OF FEATURES
echo.
echo GUI in progress.
pause
cls
echo Enjoy OpenOS!
RB1-002.bat